### ISSUE TITLE
Xcode 11.3 validation issues 

### ISSUE THREAD

**Issue by jerrymarino** [google/xctestrunner#12]
When I run xctestrunner on Xcode 11.3 I get the following error:

```  File "../xctestrunner/file/downloaded/__main__.py", line 313, in <module>
  File "../xctestrunner/file/downloaded/__main__.py", line 307, in main
  File "../xctestrunner/file/downloaded/__main__.py", line 215, in _SimulatorTest
  File "../xctestrunner/file/downloaded/__main__.py", line 170, in _RunSimulatorTest
  File "../xctestrunner/file/downloaded/__main__/xctestrunner/simulator_control/simulator_util.py", line 314, in CreateNewSimulator
  File "../xctestrunner/file/downloaded/__main__/xctestrunner/simulator_control/simulator_util.py", line 599, in _ValidateSimulatorTypeWithOsVersion
TypeError: float() argument must be a string or a number
```
When I add `13.3` to the test runner rule, under `os_version` I get:
```
xctestrunner.shared.ios_errors.IllegalArgumentError: The max OS version of iPhone 7 is 13.2. But current OS version is 13.3
```

When I add `13.2` to the test runner rule, under `os_version` I get:
```
xctestrunner.shared.ios_errors.IllegalArgumentError: The simulator os version 13.2 is not supported. Supported simulator os versions are [u'13.3'].
```

After reading the `rules_apple` documentation, I suspected the `os_version` [means _simulator runtime_](https://github.com/bazelbuild/rules_apple/blob/f4ace5b9dc19fa1a08d4b59a8f0274b75007e05d/apple/testing/default_runner/ios_test_runner.bzl#L84).

It seems like there is confusion between the SDK version Bazel is using, and the runtime version that rules_apple is using. Perhaps this is out of scope of the test runner, as `os_version` is determined by rules_apple, Bazel.

**Comment by albertdai** [comment]
Thanks for reporting that.

The root cause is xctestrunner used the command output of `xcrun --sdk iphonesimulator --show-sdk-version` as the value of max supported simulator version if `maxRuntimeVersion` is not found in the device type's profile. I will fix that and push release later.

Why we are doing this validation is `xcrun simctl create` only provides less information if the input runtime or device type is not invalid.
