### ISSUE TITLE
Unable to run tests on an iOS 9.3 iPad Retina

### ISSUE THREAD

**Issue by segiddins** [google/xctestrunner#14]
`xctestrunner.shared.ios_errors.IllegalArgumentError: The max OS version of iPad Retina is 9.255. But current OS version is 9.3`

The `maxRuntimeVersion` is `9.255.255`, which gets truncated to `9.255` before being turned into a float. Version comparison should probably be done lexicographically, rather than via `float`, since `9.3` as a version should be considered less than `9.255`

**Comment by khandpur** [comment]
@segiddins would you want to take a crack at this?

**Comment by segiddins** [comment]
It looks like https://github.com/ios-bazel-users/xctestrunner/pull/1 would accomplish this in a more general way, would you be willing to accept that patch instead of me trying to re-implement Xcode's behavior?

**Comment by khandpur** [comment]
@albertdai does that patch look okay to you?

**Comment by romoore** [comment]
+1 this is preventing me from running unit tests on 32-bit devices.

**Comment by segiddins** [comment]
(cc @jerrymarino, who wrote the linked patch)

**Comment by albertdai** [comment]
Sorry for breaking your side. I am going to fix that and will push the next release this week.

**Comment by albertdai** [comment]
It is fixed in new release 0.2.11 and will push this new release to bazel next week.
