### ISSUE TITLE
Add support for Python 3?

### ISSUE THREAD

**Issue by tinder-maxwellelliott** [google/xctestrunner#15]
Are there any plans to drop the python 2 requirement and move to python 3 to use this library? If so I could assist in that effort

**Comment by albertdai** [comment]
Yes. Since PY3 is installed on macOS Catalina right now, we have planed to migrate to PY3.

Any help is appreciated.

**Comment by jin** [comment]
@albertdai would your team be open to reviewing and accepting a PR from the community?

**Comment by segiddins** [comment]
I started working on python3 support, but it's a bit hard to tell if I've broken anything since this repo has no tests -- would rules_apple tests passing pointing to a python3 par be sufficient to be confident the changes work?

**Comment by albertdai** [comment]
The xctestrunner support python3 right now.
