### ISSUE TITLE
UIScreen returning wrong values when unit testing without host library

### ISSUE THREAD

**Issue by acecilia** [google/xctestrunner#17]
Hi:

I noticed that when unit testing with the `ios_unit_test`rule:
- `UIScreen.main.scale` returns 1.
- `UIScreen.main.bounds.size` returns 0 for height and width.

Reading the docs for `ios_unit_test` it says that:

`ios_unit_test targets can work in two modes: as app or library tests. If the test_host attribute is set to an ios_application target, the tests will run within that application's context. If no test_host is provided, the tests will run outside the context of an iOS application. Because of this, certain functionalities might not be present (e.g. UI layout, NSUserDefaults). You can find more information about app and library testing for Apple platforms here.
`

Up until this point makes sense.

But, then, how is it possible that running unit tests from xcode without `hostApp`, accessing `UIScreen` properties returns the correct values for the simulator used? How does Apple do it?

My use case is snapshot testing: at the moment I do snapshot testing without `hostApp`. With bazel I need to use `hostApp` in order to access the screen properties (scale and size), which sometimes results in slightly different snapshots than the ones taken using Xcode, breaking my tests.

Would it be possible to configure the test runner, so it passes this information correctly through `UIScreen`?

Thanks :)

**Comment by keith** [comment]
This is expected, if the simulator isn't booted you won't get valid values here, but you will get faster test running.

To make xctestrunner boot a simulator for you, you need a test host.

If you want to use a custom simulator so it matches the same one in Xcode you can define which device you want on a custom test runner rule like:

```
ios_test_runner(
    name = "your_runner",
    device_type = "whatever",
    visibility = ["//visibility:public"],
)
```

And set it to the `runner` property on your `ios_unit_test`. That way you should be able to get consistent results between Xcode and Bazel

**Comment by acecilia** [comment]
Thanks @keith ! :)

I understand looking at the documentation that this is expected behavior, but what I would like to know is:
* How is it possible that running unit tests from xcode without `hostApp`, accessing `UIScreen` properties returns the correct values for the simulator used? How does Apple do it?
* Would it makes sense and is it possible to make the runner pass correct values for `UIScreen` even when running without `appHost`?

**Comment by keith** [comment]
They boot the simulator in Xcode regardless of whether or not you have a test host, that's where this test runner differs, it uses not having a test host as an indication that you don't need those APIs. In theory you could change this runner, or write your own, that booted the simulator no matter what at the cost of some test running performance

**Comment by mattrobmattrob** [comment]
I ran into this same issue and unfortunately running our test bundles within a test host is making them unstable.

Using `UIScreen.main.scale` as my confirmation that it's running correctly, this is the fix that allows test bundle + no test host to work for us: https://github.com/reddit/xctestrunner/commit/f32b9ac6c59d886caa7d53795f239f35a182c714

With a snapshot test runner defined (like @Keith mentioned):

```Starlark
load("@build_bazel_rules_apple//apple/testing/default_runner:ios_test_runner.bzl", "ios_test_runner")

ios_test_runner(
    name = "standard_snapshot_runner",
    device_type = "iPhone 8 Plus",
    visibility = ["//visibility:public"],
)
```

We do the following in CI using that change:

1. Define `ios_unit_test` with `test_host = None` + `runner = :standard_snapshot_runner`.
2. Boot a simulator on the macOS host.
3. Pass the simulator to the `bazel coverage` invocation using `--test_arg=--destination=platform=ios_simulator,id=$SIMULATOR_ID`.

Removing the `--standalone` from `xctestrunner` populates the `UIScreen` values as expected but requires the simulator to be booted. I can try to refactor our fork into a useful PR for `xctestrunner` if folks would find it useful.
