### ISSUE TITLE
Latest xctestrunner is not compatible with remote execution

### ISSUE THREAD

**Issue by thii** [google/xctestrunner#38]
All of our tests failed with this same error after updating xctestrunner to the latest commit (https://github.com/google/xctestrunner/commit/7f8fc81b10c8d93f09f6fe38b2a3f37ba25336a6). Running them locally doesn't reproduce the problem.

```
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
Executing tests from //sometest
-----------------------------------------------------------------------------
2021-10-29 23:01:13,665 Creating a new simulator:
Name: New-iPhone 13 Pro Max-15.0
OS: iOS 15.0
Type: iPhone 13 Pro Max
2021-10-29 23:01:14,639 Created new simulator 14753767-9861-450F-BF51-FF192687DF13.
2021-10-29 23:01:14,688 Will consider the test as test type logic_test to run.
An error was encountered processing the command (domain=com.apple.CoreSimulator.SimError, code=404):
Invalid device: The specified device is not available for spawning processes.
2021-10-29 23:01:18,106 Deleting simulator 14753767-9861-450F-BF51-FF192687DF13 asynchronously.
2021-10-29 23:01:18,112 Done.
```

**Comment by thii** [comment]
cc @albertdai

**Comment by albertdai** [comment]
Sorry for breaking your side. Let me try to figure out what's going on and fix that.

**Comment by albertdai** [comment]
I never saw this issue before and I am not sure if it is related to DEVELOPER_DIR environment. I checked in a13ec9de45d225620dd4b5e30b23bdc663631f31 and please verify if the issue is still there

**Comment by thii** [comment]
I've verified that https://github.com/google/xctestrunner/commit/a13ec9de45d225620dd4b5e30b23bdc663631f31 fixes the issue on our side - thanks for the quick fix!

Here's a bit more information regarding our setup if it makes easier to debug the root cause here: our remote executors are provisioned with multiple Xcode versions (12.5.1, 13, and 13.1), and what we're running is Xcode 13.

**Comment by albertdai** [comment]
Good to know it can fix the issue.
